# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kenny/latihan_c++/neural_network_test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kenny/latihan_c++/neural_network_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kenny/latihan_c++/neural_network_test/CMakeFiles /home/kenny/latihan_c++/neural_network_test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kenny/latihan_c++/neural_network_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named neural_network_test

# Build rule for target.
neural_network_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 neural_network_test
.PHONY : neural_network_test

# fast build rule for target.
neural_network_test/fast:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/build
.PHONY : neural_network_test/fast

source/acfunc.o: source/acfunc.cpp.o

.PHONY : source/acfunc.o

# target to build an object file
source/acfunc.cpp.o:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/acfunc.cpp.o
.PHONY : source/acfunc.cpp.o

source/acfunc.i: source/acfunc.cpp.i

.PHONY : source/acfunc.i

# target to preprocess a source file
source/acfunc.cpp.i:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/acfunc.cpp.i
.PHONY : source/acfunc.cpp.i

source/acfunc.s: source/acfunc.cpp.s

.PHONY : source/acfunc.s

# target to generate assembly for a file
source/acfunc.cpp.s:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/acfunc.cpp.s
.PHONY : source/acfunc.cpp.s

source/cu.o: source/cu.cpp.o

.PHONY : source/cu.o

# target to build an object file
source/cu.cpp.o:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/cu.cpp.o
.PHONY : source/cu.cpp.o

source/cu.i: source/cu.cpp.i

.PHONY : source/cu.i

# target to preprocess a source file
source/cu.cpp.i:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/cu.cpp.i
.PHONY : source/cu.cpp.i

source/cu.s: source/cu.cpp.s

.PHONY : source/cu.s

# target to generate assembly for a file
source/cu.cpp.s:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/cu.cpp.s
.PHONY : source/cu.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/mytraining.o: source/mytraining.cpp.o

.PHONY : source/mytraining.o

# target to build an object file
source/mytraining.cpp.o:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/mytraining.cpp.o
.PHONY : source/mytraining.cpp.o

source/mytraining.i: source/mytraining.cpp.i

.PHONY : source/mytraining.i

# target to preprocess a source file
source/mytraining.cpp.i:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/mytraining.cpp.i
.PHONY : source/mytraining.cpp.i

source/mytraining.s: source/mytraining.cpp.s

.PHONY : source/mytraining.s

# target to generate assembly for a file
source/mytraining.cpp.s:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/mytraining.cpp.s
.PHONY : source/mytraining.cpp.s

source/nnbp.o: source/nnbp.cpp.o

.PHONY : source/nnbp.o

# target to build an object file
source/nnbp.cpp.o:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/nnbp.cpp.o
.PHONY : source/nnbp.cpp.o

source/nnbp.i: source/nnbp.cpp.i

.PHONY : source/nnbp.i

# target to preprocess a source file
source/nnbp.cpp.i:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/nnbp.cpp.i
.PHONY : source/nnbp.cpp.i

source/nnbp.s: source/nnbp.cpp.s

.PHONY : source/nnbp.s

# target to generate assembly for a file
source/nnbp.cpp.s:
	$(MAKE) -f CMakeFiles/neural_network_test.dir/build.make CMakeFiles/neural_network_test.dir/source/nnbp.cpp.s
.PHONY : source/nnbp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... neural_network_test"
	@echo "... edit_cache"
	@echo "... source/acfunc.o"
	@echo "... source/acfunc.i"
	@echo "... source/acfunc.s"
	@echo "... source/cu.o"
	@echo "... source/cu.i"
	@echo "... source/cu.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/mytraining.o"
	@echo "... source/mytraining.i"
	@echo "... source/mytraining.s"
	@echo "... source/nnbp.o"
	@echo "... source/nnbp.i"
	@echo "... source/nnbp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

